### ISSUE TITLE
Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PMRF module for custom nodes: unexpected EOF, expected 1583311 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by Andy2024mm** [2kpr/ComfyUI-PMRF#12]
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PMRF\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PMRF\nodes.py", line 47, in <module>
    pmrf = MMSERectifiedFlow.from_pretrained(pmrf_path).to(device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\hub_mixin.py", line 569, in from_pretrained
    instance = cls._from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\hub_mixin.py", line 789, in _from_pretrained
    model = cls(**model_kwargs)
            ^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PMRF\lightning_models\mmse_rectified_flow.py", line 82, in __init__
    self.fid = FrechetInceptionDistance(reset_real_features=True, normalize=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchmetrics\image\fid.py", line 326, in __init__
    self.inception = NoTrainInceptionV3(name="inception-v3-compat", features_list=[str(feature)])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchmetrics\image\fid.py", line 59, in __init__
    super().__init__(name, features_list, feature_extractor_weights_path)
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch_fidelity\feature_extractor_inceptionv3.py", line 83, in __init__
    state_dict = load_state_dict_from_url(URL_INCEPTION_V3, progress=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\hub.py", line 769, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location, weights_only=weights_only)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1114, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1357, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 1583311 more bytes. The file might be corrupted.

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PMRF module for custom nodes: unexpected EOF, expected 1583311 more bytes. The file might be corrupted.

**Comment by liaochenlanruo** [comment]
Same error

**Comment by rhf2137** [comment]
相同问题。将nodes.py的这3行关闭“pmrf_path = os.path.join(folder_paths.models_dir, "pmrf")
upsampler = set_realesrgan()
pmrf = MMSERectifiedFlow.from_pretrained(pmrf_path).to(device=device)
”后，能正常加载，可运行时以出现“PMRF
name 'pmrf' is not defined”的报错。

**Comment by rhf2137** [comment]
现在把“\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PMRF\lightning_models“目录下mmse_rectified_flow.py文件中的“if 'flow' in stage:
            self.fid = FrechetInceptionDistance(reset_real_features=True, normalize=True)
            self.inception_score = InceptionScore(normalize=True)
”这3行关闭“#if 'flow' in stage:
           # self.fid = FrechetInceptionDistance(reset_real_features=True, normalize=True)
            #self.inception_score = InceptionScore(normalize=True)
”，成功运行，不报错。注意安装pytorcho要不高于：pytorch version: 2.4.1+cu124

**Comment by ringtmc** [comment]
> 现在把“\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-PMRF\lightning_models“目录下mmse_rectified_flow.py文件中的“if 'flow' in stage: self.fid = FrechetInceptionDistance(reset_real_features=True, normalize=True) self.inception_score = InceptionScore(normalize=True) ”这3行关闭“#if 'flow' in stage: # self.fid = FrechetInceptionDistance(reset_real_features=True, normalize=True) #self.inception_score = InceptionScore(normalize=True) ”，成功运行，不报错。注意安装pytorcho要不高于：pytorch version: 2.4.1+cu124

谢谢胸弟，解决了，Orz
